### ISSUE TITLE
scp get() not accepting wildcard"*"

### ISSUE THREAD

**Issue by zaaaaim** [jbardin/scp.py#64] opened 2015-10-26 00:40 UTC
https://bitbucket.org/pypa/pypi/issues/349/get-of-scpscpclient-not-accepting-wildcard

I recently upgraded the scp to 0.10.2 after years, and the get() no longer accept wildcard "*" to get all the files from a specific folder.

I have updated details there as well.

**Comment by remram44** [comment] 2015-10-26 04:59
Duplicate of #48

**Closed** 2015-10-27 22:21 UTC
