### ISSUE TITLE
time.sleep() after scp

### ISSUE THREAD

**Issue by bott17** [jbardin/scp.py#78] opened 2016-09-07 07:50 UTC
Im using the lib in a automatic testing scripts and notice that if  send a config file via scp and using it immediately after (in my case, usinga  api service that used this conf file) the OS dont notice the changes in file.
I solved this using a wait() after the scp finish

**Comment by remram44** [comment] 2016-09-07 15:28
What is wait()? Do you mean `time.sleep()` or equivalent?

This is weird because this lib is supposed to block until the transfer is finished 😮

**Comment by bott17** [comment] 2016-09-07 15:38
Sorry, time.sleep() its correct, not wait()

yeah that was my face when i see that :O
Maybe SO need some time to make a flush or something... I tests it on AWS-EC2

**Comment by remram44** [comment] 2017-11-08 16:07
This is surprising to me because the `tej` library I wrote [uploads files and executes them immediately](https://github.com/VisTrails/tej/blob/1fd51540a2f811667a29a74f390e21a2984a4699/tej/submission.py#L450-L459), and never ran into this issue. Are you sure scp has returned when you access the file? Are you using multiple threads in your client?

**Comment by bott17** [comment] 2017-11-08 21:08
I think so, only 1 thread and wait for scp completed to continue. I don´t have access to the code anymore, sorry :/

**Comment by remram44** [comment] 2017-11-09 14:53
I just tested this and could not reproduce:

```python
from paramiko import SSHClient
from scp import SCPClient

# Connect via SSH
ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect('ec2-server')

# Open a shell
chan = ssh.get_transport().open_session()
chan.exec_command('/bin/sh')

# Put file
scp = SCPClient(ssh.get_transport())
scp.put('test.txt', 'test.txt')

# Test that the file exists
chan.send('exec cat test.txt 2>&1\n')
out = chan.recv(4096)
while out:
    print(repr(out))
    out = chan.recv(4096)
print(chan.recv_exit_status())

chan.close()
scp.close()
ssh.close()
```

I am going to go ahead and close this. Let me know if you run into the issue again, but really that would be a bug in the server, not this client library 🤔

**Closed** 2017-11-09 14:53 UTC
Labels: bug, waiting on author
