### ISSUE TITLE
Add support for get() to keep downloaded file in memory via a BytesIO object as the "local_file"

### ISSUE THREAD

**Issue by gillhofer** [jbardin/scp.py#182] opened 2023-07-27 06:43 UTC
Currently `get()` requires one to specify a path to a local file. This enforces the user to store the file to a path on the filesystem. 
Add support for get() to keep downloaded File in memory via a BytesIO Object as the "local_file".

**Comment by remram44** [comment] 2023-07-27 14:42
Duplicate of #94

**Closed by remram44** 2023-07-27 14:42 UTC
