### ISSUE TITLE
Get data into file-like object - getfo

### ISSUE THREAD

**Issue by stevstrong** [jbardin/scp.py#168] opened 2021-11-19 11:22 UTC
Hi,
I have an application where I would like to have the transferred data in a file-like object instead of storing the file on local drive.
Would it make sence to implement such kind of function?
If there is no plan to add it to this repo, I would appreciate any hint which helps me to implement that myself.
Thanx in advance.

**Comment by remram44** [comment] 2021-11-19 15:02
Duplicate of #94

**Closed by remram44** 2021-11-19 15:02 UTC
