### ISSUE TITLE
Recursive get doesnt seem to work

### ISSUE THREAD

**Issue by patcable** [jbardin/scp.py#62] opened 2015-09-20 17:22 UTC
Hi! Thanks for writing scp; it's made my life a lot easier!

I am running into a problem with recursive gets that I think may be unicode related, but I'm not entirely sure. I'm running scp 0.10.2 on Python 2.7.6. In my code, I have:
```python
scp.get(runtime_dir + "/*.txt", local_path=args.test_id)
```
Indeed, this works fine via scp on the command line (`scp ubuntu@192.168.252.147:/home/ubuntu/testdir/module/*.txt .`). However, when I try using the module, I get:

```
Traceback (most recent call last):
  File "./script.py", line 116, in <module>
    scp.get(runtime_dir + "/*.txt", local_path=args.test_id)
  File "/Users/patcable/Virtualenvs/osclient/lib/python2.7/site-packages/scp.py", line 198, in get
    self._recv_all()
  File "/Users/patcable/Virtualenvs/osclient/lib/python2.7/site-packages/scp.py", line 348, in _recv_all
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: scp: /home/ubuntu/testdir/module/*.txt: No such file or directory
```

Am I missing something simple? It seems like this should work; for now I just work around by using os.subprocess, but figured it'd be neat if it worked in the module. In any case, thanks for your time!

**Comment by remram44** [comment] 2015-09-20 17:33
Duplicate of #48 

Recursive transfers do work, but wildcards don't. You can transfer the whole directory `/home/ubuntu/testdir/module` (if it doesn't contain anything apart from the `.txt` files).

**Comment by patcable** [comment] 2015-09-20 17:35
Ahh, oops, I used the wrong word. Not enough coffee. 

Thanks for the pointer!

**Closed** 2015-09-20 17:45 UTC
