### ISSUE TITLE
Downloading many files on one channel, randomly I get a SSHException: channel is not open

### ISSUE THREAD

**Issue by mar-ses** [jbardin/scp.py#135] opened 2019-10-25 11:56 UTC
This might not be a bug, perhaps I'm using it wrong. I can see other issues here seem to also reference this, and on stackoverflow regarding paramiko, however I don't understand paramiko (and scp I guess) to understand which way the comments are pointing.

Essentially, I open a channel the normal way:

```
    ssh = SSHClient()
    ssh.load_system_host_keys()
    ssh.connect('address.com',
                username='username',
                password='password')
    scp = SCPClient(ssh.get_transport())
```

And then I start downloading a few hundred files, let's say it's a bunch of for loops:

```
for file_path, local_path in locations:
    scp.get(file_path, local_path)
```

There are several of these by the way. It essentially goes as planned, however at a random point it fails with the error:

`SSHException: Channel is not open`

This seems to be random, so apparently the channel is closing or something? stackoverflow issues on `paramiko` seem to mention you need to open a new channel after each command; but I assumed `scp` would do this on its own? It seems to have no problem getting through a few hundred commands, but after a while it fails, and I don't know why.

Is there something I'm not doing right or what? Other than having an except ... : reload the whole SSHClient() thing, what can I do?

---------------------------------------------
Off-topic: you may have noticed in my first bit of code that I'm manually entering the password as a string, which is obviously written out in my code files. First of all, I just remembered I need to not to upload this package to github, which I nearly did. Moreover, I get the feeling that even keeping this thing my computer, some admin would scream at me. Is there a better way to do this without having cluster account passwords stored in your source code?

**Comment by remram44** [comment] 2019-10-25 19:03
Duplicate of #105. We should really fix this...

**Comment by remram44** [comment] 2019-10-25 19:06
Re: password, you can either ask the user to type it in when you run the script (`input()`), or put it in a separate file that you don't check in to version control with your code. You can also use a private key instead of a password (paramiko supports that) though you then have to deal with the passphrase (or not encrypt it).

**Closed** 2019-10-25 19:06 UTC
