### ISSUE TITLE
Remote Globs

### ISSUE THREAD

**Issue by AaronNBrock** [jbardin/scp.py#106] opened 2018-04-10 19:46 UTC
I'm trying to recreate the following command using scp.py

```bash
scp -P 122 admin@example.com:/path/to/glob* .
```

From what I can tell this is not possible, could this feature be added?  (Or if it already exists, how do you use it?)

**Comment by remram44** [comment] 2018-04-11 08:27
Duplicate of #48, #64, #93, and #101

Please use the search :wink:

**Closed by remram44** 2018-04-11 08:27 UTC
