### ISSUE TITLE
Cannot get() by wildcard from a remote host

### ISSUE THREAD

**Issue by ss8913** [jbardin/scp.py#101] opened 2018-02-12 07:24 UTC
This thing is great, except you cannot specify wildcards in get() ie, get("/var/log/messages*") will say that it doesn't exist, because it's looking for a literal single file named that.  specifying a single file that exists, with the same code works great, so it looks to me like it's definitely a wildcarding issue.  Is there a workaround, is this a bug, or is this not how the code is intended to be used and won't be fixed/changed?

**Comment by remram44** [comment] 2018-02-12 10:32
This is possible but not the default behavior

Duplicate of #48 #64 and #93

**Closed** 2018-02-12 10:32 UTC
Labels: duplicate
